# Generated by Django 4.0.4 on 2022-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=50)),
                ('vaqti', models.DateTimeField()),
                ('malumot', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('bajarildi', 'bajarildi'), ('bajarilgani yoq', 'bajarilgani yoq')], max_length=50)),
            ],
        ),
    ]
